#pragma once

#define APP_NAME "Home Control Panel"
#define APP_VERSION "1.4.1"
#define APP_DISPLAY_ROTATION 90
#define APP_DEFAULT_BACKLIGHT 80
#define APP_DEFAULT_SCREEN_TIMEOUT_SECONDS 120U
#define APP_LOOP_TASK_STACK_BYTES (16U * 1024U)
#define APP_TIMEZONE_POSIX "CST6CDT,M3.2.0,M11.1.0"

#define PANEL_CONFIG_PATH "/panel.json"
#define PANEL_MAX_MODULES 8
#define PANEL_MODULE_ID_LEN 24
#define PANEL_MAX_MEDIA_SHORTCUTS 3
#define PANEL_MEDIA_SHORTCUT_LABEL_LEN 40
#define PANEL_MEDIA_ENTITY_ID_LEN 96

#define WEB_MANAGER_PORT 80
#define WEB_MANAGER_DEFAULT_USER "admin"
#define WEB_MANAGER_DEFAULT_PASSWORD "homepanel"

#define HA_HTTP_CONNECT_TIMEOUT_MS 3500
#define HA_HTTP_TIMEOUT_MS 5000
#define HA_HTTP_INTER_REQUEST_GAP_MS 1000UL
#define HA_COMMAND_RETRY_DELAY_MS 350UL
#define HA_COMMAND_MAX_ATTEMPTS 2U
#define HA_WORKER_STACK_BYTES 16384
#define HA_WORKER_PRIORITY 0
#define HA_HEALTH_INTERVAL_MS 300000UL
#define HA_BOOT_NETWORK_STABLE_MS 10000UL
#define HA_TLS_ALLOW_INSECURE 1
#define HA_WS_RECONNECT_MS 5000UL
#define HA_DISCOVERY_TIMEOUT_MS 15000UL
#define HA_MAX_AREA_ENTITIES 48
#define HA_MAX_ROOM_CONTROLS 4
#define HA_MAX_AREA_SCENES 3
#define HA_MAX_MEDIA_PLAYERS 4
#define HA_MAX_MEDIA_SOURCES 4
#define HA_MAX_MEDIA_FAVORITES 3
#define HA_MEDIA_SOURCE_NAME_LEN 48
#define HA_MEDIA_CONTENT_ID_LEN 192
#define HA_MEDIA_CONTENT_TYPE_LEN 48
#define HA_MEDIA_ARTWORK_URL_LEN 512
#define HA_MEDIA_ARTWORK_MAX_BYTES (256U * 1024U)
#define HA_MEDIA_ARTWORK_TIMEOUT_MS 7000UL
#define HA_ACTION_QUEUE_DEPTH 8

#define HOSTED_C6_AUTO_UPDATE 1

#define BATTERY_ADC_PIN 52
#define BATTERY_VOLTAGE_MULTIPLIER 1.680f
#define BATTERY_SAMPLE_INTERVAL_MS 15000UL
#define BATTERY_ADC_SAMPLE_COUNT 12
#define BATTERY_VALID_MIN_MV 2800U
#define BATTERY_VALID_MAX_MV 4500U

#if __has_include("app_secrets.h")
#include "app_secrets.h"
#endif
#ifndef WIFI_SSID
#define WIFI_SSID "YOUR_WIFI_SSID"
#endif
#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#endif
#ifndef WEB_MANAGER_USER
#define WEB_MANAGER_USER WEB_MANAGER_DEFAULT_USER
#endif
#ifndef WEB_MANAGER_PASSWORD
#define WEB_MANAGER_PASSWORD WEB_MANAGER_DEFAULT_PASSWORD
#endif
